---
# tasks file for docker-registry
- name: Log into DockerHub
  docker_login:
    username: 142033
    password: azertyazerty
    email: siwar.hassine@esprit.tn
- name: Push to docker hub
  docker_image:
    name: 142033/myapp
    repository: 142033/myapp
    tag: latest
    source: local
    push: yes
